[features]
seeds = false
skip-lint = false
[programs.localnet]
token_auth = "DQHN7u5tejZPTCLmqaH8HqkLMXHx83CZbzyv7BAbhn8D"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/adrou/Desktop/solana_stuff/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
